//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevIO.App.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Traducao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Traducao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevIO.App.Language.Traducao", typeof(Traducao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo?.
        /// </summary>
        public static string Ativo {
            get {
                return ResourceManager.GetString("Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro .
        /// </summary>
        public static string BairroLogradouro {
            get {
                return ResourceManager.GetString("BairroLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep da Rua.
        /// </summary>
        public static string CepLogradouro {
            get {
                return ResourceManager.GetString("CepLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Cidade.
        /// </summary>
        public static string CidadeLogradouro {
            get {
                return ResourceManager.GetString("CidadeLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento Endereço.
        /// </summary>
        public static string ComplementoLogradouro {
            get {
                return ResourceManager.GetString("ComplementoLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Alteração.
        /// </summary>
        public static string DataAlteracao {
            get {
                return ResourceManager.GetString("DataAlteracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Cadastro.
        /// </summary>
        public static string DataCadastro {
            get {
                return ResourceManager.GetString("DataCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do Produto.
        /// </summary>
        public static string DescricaoProduto {
            get {
                return ResourceManager.GetString("DescricaoProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Fornecedor.
        /// </summary>
        public static string DocFornecedor {
            get {
                return ResourceManager.GetString("DocFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla Estado.
        /// </summary>
        public static string EstadoLogradouro {
            get {
                return ResourceManager.GetString("EstadoLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem do Produto.
        /// </summary>
        public static string ImagemProduto {
            get {
                return ResourceManager.GetString("ImagemProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Fornecedor.
        /// </summary>
        public static string NomeFornecedor {
            get {
                return ResourceManager.GetString("NomeFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Rua.
        /// </summary>
        public static string NomeLogradouro {
            get {
                return ResourceManager.GetString("NomeLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Produto.
        /// </summary>
        public static string NomeProduto {
            get {
                return ResourceManager.GetString("NomeProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número da Rua.
        /// </summary>
        public static string NumeroLogradouro {
            get {
                return ResourceManager.GetString("NumeroLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto em Promoção?.
        /// </summary>
        public static string PromocaoProduto {
            get {
                return ResourceManager.GetString("PromocaoProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Fornecedor.
        /// </summary>
        public static string TipoFornecedor {
            get {
                return ResourceManager.GetString("TipoFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validade do Produto.
        /// </summary>
        public static string ValidadeProduto {
            get {
                return ResourceManager.GetString("ValidadeProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor do Produto.
        /// </summary>
        public static string ValorProduto {
            get {
                return ResourceManager.GetString("ValorProduto", resourceCulture);
            }
        }
    }
}
